[package]
name = "tpm-tool"
version = "0.1.0"
edition = "2024"

[features]
default = ["rustcrypto"]

rustcrypto = ["dep:aes-gcm", "dep:sha1", "dep:sha3"]
openssl = ["dep:openssl"]

bundled = ["rusqlite/bundled"]
bundled-windows = ["rusqlite/bundled-windows"]

[dependencies]
aes-gcm = { version = "0.10", optional = true }
asn1 = "0.24"
bitflags = "2.13"
block-padding = "0.4"
directories = "6.0"
hex = "0.4"
openssl = { version = "0.10", optional = true }
rand = "0.8"
rusqlite = { version = "0.40", default-features = false, features = ["fallible_uint"] }
sha1 = { version = "0.10", optional = true }
sha2 = "0.10"
sha3 = { version = "0.10", optional = true }
thiserror = "2.0.18"
tracing = "0.1"
zeroize = { version = "1.9", features = ["derive"]}

[target.'cfg(target_os = "windows")'.dependencies]
aes = "0.8"
hmac = "0.12"
rsa = "0.9"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_TpmBaseServices",
] }

[target.'cfg(target_os = "linux")'.dependencies]
tss-esapi = "7.7"

[dev-dependencies]
tempfile = "3.27"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
