[package]
name = "tpm-tool"
version = "0.1.0"
edition = "2024"

[features]
default = ["rustcrypto"]
rustcrypto = ["dep:aes-gcm", "dep:sha1", "dep:sha2", "dep:sha3", "dep:sm3"]
openssl = ["dep:openssl"]

[dependencies]
aes-gcm = { version = "0.10", optional = true }
asn1 = "0.24"
base64 = "0.22"
block-padding = "0.4"
directories = "6.0"
getrandom = "0.4"
openssl = { version = "0.10", optional = true }
rusqlite = "0.40"
sha1 = { version = "0.10", optional = true }
sha2 = { version = "0.10", optional = true }
sha3 = { version = "0.10", optional = true }
sm3 = { version = "0.4", optional = true }
thiserror = "2.0.18"
tracing = "0.1"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_TpmBaseServices",
] }
zeroize = "1.9"

[target.'cfg(target_os = "linux")'.dependencies]
tss-esapi = "7.7"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

