use crate::Result;

use super::Context;

impl Context {
    /// Returns `num_bytes` of random data generated by the TPM.
    ///
    /// Passing zero returns an empty vector without issuing a TPM command. Nonzero requests
    /// require a provisioned context.
    pub fn get_random(&mut self, num_bytes: usize) -> Result<Vec<u8>> {
        if num_bytes == 0 {
            return Ok(Vec::new());
        }

        let session_salt_handle = self.load_session_salt_handle()?;
        self.backend.get_random(num_bytes, session_salt_handle)
    }
}
